# Generated by Django 2.0.4 on 2018-04-09 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edc_action_item', '0005_auto_20180409_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalactionitem',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Action Item'},
        ),
        migrations.AlterModelOptions(
            name='historicalactionitemupdate',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical action item update'},
        ),
        migrations.AlterField(
            model_name='historicalactionitem',
            name='parent_action_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='edc_action_item.ActionItem'),
        ),
    ]
